export 'package:cinemapedia/domain/repositories/actors_repository.dart';
export 'package:cinemapedia/presentation/providers/actors/actors_by_movie_provider.dart';
export 'package:cinemapedia/presentation/providers/movies/movies_provider.dart';
export 'package:cinemapedia/domain/repositories/movies_repository.dart';
export 'package:cinemapedia/presentation/providers/movies/movies_slideshow_provider.dart';
export 'search/search_movies_provider.dart';
export 'storage/local_storage_provider.dart';
export 'storage/favorite_movies_provider.dart';
export 'package:cinemapedia/presentation/providers/movies/movie_info_provider.dart';
